import { Router, Request, Response } from 'express';
import { Octokit } from '@octokit/rest';
import { configLoader } from '../config/configLoader';
import { authMiddleware } from '../auth/authMiddleware';
import { asyncHandler, ValidationError, AppError } from '../utils/errorHandler';
import { logger } from '../utils/logger';

const log = logger.child('GitHubExporter');

/**
 * Generates a complete project structure as file content map.
 * This is what gets pushed to GitHub — a fully working codebase.
 */
function generateProjectFiles(config: ReturnType<typeof configLoader.getConfig>): Record<string, string> {
  const files: Record<string, string> = {};

  // ── README.md ──────────────────────────────────────────────────────
  if (config.export.github.includeReadme) {
    const entityList = Object.keys(config.database.entities)
      .map((e) => `  - ${e}`)
      .join('\n');

    files['README.md'] = `# ${config.app.name}

> ${config.app.description}

## Tech Stack
- **Frontend**: Next.js + Tailwind CSS
- **Backend**: Node.js + TypeScript + Express
- **Database**: PostgreSQL

## Entities
${entityList}

## Setup

### Prerequisites
- Node.js 18+
- PostgreSQL 15+

### Backend
\`\`\`bash
cd backend
cp .env.example .env
# Edit .env with your database credentials
npm install
npm run dev
\`\`\`

### Frontend
\`\`\`bash
cd frontend
cp .env.example .env.local
npm install
npm run dev
\`\`\`

## API Endpoints
Base URL: \`${config.api.prefix}\`

${Object.entries(config.api.endpoints)
  .map(
    ([name, ep]) => `### ${name}
${ep.operations.map((op) => {
  switch (op) {
    case 'list': return `- \`GET ${config.api.prefix}/${name}\``;
    case 'get': return `- \`GET ${config.api.prefix}/${name}/:id\``;
    case 'create': return `- \`POST ${config.api.prefix}/${name}\``;
    case 'update': return `- \`PUT ${config.api.prefix}/${name}/:id\``;
    case 'delete': return `- \`DELETE ${config.api.prefix}/${name}/:id\``;
    default: return '';
  }
}).join('\n')}`
  )
  .join('\n\n')}

## Authentication
${config.auth.methods
  .filter((m) => m.enabled)
  .map((m) => `- ${m.type.replace('_', ' ').replace(/\b\w/g, (l) => l.toUpperCase())}`)
  .join('\n')}

## Languages
${config.i18n.supportedLanguages.join(', ')}

---
*Generated by AI App Generator v${config.app.version}*
`;
  }

  // ── .env.example ─────────────────────────────────────────────────
  if (config.export.github.includeEnvExample) {
    files['backend/.env.example'] = `PORT=4000
NODE_ENV=development
DATABASE_URL=postgresql://postgres:password@localhost:5432/${config.app.name.toLowerCase().replace(/\s+/g, '_')}
JWT_SECRET=change-me-in-production
JWT_REFRESH_SECRET=change-me-in-production
CONFIG_PATH=../config/app-config.json
FRONTEND_URL=http://localhost:3000
SMTP_HOST=smtp.mailtrap.io
SMTP_PORT=2525
SMTP_USER=
SMTP_PASS=
SMTP_FROM=noreply@app.com
`;

    files['frontend/.env.example'] = `NEXT_PUBLIC_API_URL=http://localhost:4000
NEXT_PUBLIC_APP_NAME=${config.app.name}
`;
  }

  // ── Dockerfile ──────────────────────────────────────────────────
  if (config.export.github.includeDockerfile) {
    files['backend/Dockerfile'] = `FROM node:20-alpine AS builder
WORKDIR /app
COPY package*.json ./
RUN npm ci
COPY . .
RUN npm run build

FROM node:20-alpine
WORKDIR /app
COPY package*.json ./
RUN npm ci --production
COPY --from=builder /app/dist ./dist
COPY --from=builder /app/../config ../config
EXPOSE 4000
CMD ["node", "dist/index.js"]
`;

    files['docker-compose.yml'] = `version: '3.8'
services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: ${config.app.name.toLowerCase().replace(/\s+/g, '_')}
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build: ./backend
    ports:
      - "4000:4000"
    environment:
      DATABASE_URL: postgresql://postgres:password@db:5432/${config.app.name.toLowerCase().replace(/\s+/g, '_')}
    depends_on:
      - db

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    environment:
      NEXT_PUBLIC_API_URL: http://backend:4000
    depends_on:
      - backend

volumes:
  pgdata:
`;
  }

  // ── Config ──────────────────────────────────────────────────────
  files['config/app-config.json'] = JSON.stringify(config, null, 2);

  // ── .gitignore ──────────────────────────────────────────────────
  files['.gitignore'] = `node_modules/
dist/
.env
.env.local
.next/
*.log
`;

  return files;
}

/**
 * Creates the GitHub export router.
 * Pushes the generated project structure to a new or existing GitHub repository.
 */
export function createExportRouter(): Router {
  const router = Router();

  router.post(
    '/github',
    authMiddleware,
    asyncHandler(async (req: Request, res: Response) => {
      const config = configLoader.getConfig();

      if (!config.export.github.enabled) {
        throw new AppError('GitHub export is disabled in config', 403);
      }

      const { repoName, repoDescription, isPrivate = true } = req.body;

      if (!repoName) {
        throw new ValidationError('Repository name is required');
      }

      const githubToken = process.env.GITHUB_TOKEN;
      if (!githubToken) {
        throw new AppError('GitHub token not configured on the server', 500);
      }

      const octokit = new Octokit({ auth: githubToken });

      try {
        // 1. Get authenticated user
        const { data: ghUser } = await octokit.users.getAuthenticated();
        log.info(`GitHub user: ${ghUser.login}`);

        // 2. Create or get repo
        let repoOwner = ghUser.login;
        let repoExists = false;

        try {
          await octokit.repos.get({ owner: repoOwner, repo: repoName });
          repoExists = true;
          log.info(`Repository ${repoName} already exists, will update`);
        } catch {
          // Repo doesn't exist — create it
          const { data: newRepo } = await octokit.repos.createForAuthenticatedUser({
            name: repoName,
            description: repoDescription || config.app.description,
            private: isPrivate,
            auto_init: true,
          });
          repoOwner = newRepo.owner.login;
          log.info(`Created repository: ${newRepo.full_name}`);
        }

        // 3. Generate project files
        const files = generateProjectFiles(config);

        // 4. Get the default branch reference
        const { data: ref } = await octokit.git.getRef({
          owner: repoOwner,
          repo: repoName,
          ref: 'heads/main',
        }).catch(() =>
          octokit.git.getRef({
            owner: repoOwner,
            repo: repoName,
            ref: 'heads/master',
          })
        );

        const latestCommitSha = ref.object.sha;

        // 5. Get the tree of the latest commit
        const { data: latestCommit } = await octokit.git.getCommit({
          owner: repoOwner,
          repo: repoName,
          commit_sha: latestCommitSha,
        });

        // 6. Create blobs for each file
        const treeItems = [];
        for (const [path, content] of Object.entries(files)) {
          const { data: blob } = await octokit.git.createBlob({
            owner: repoOwner,
            repo: repoName,
            content: Buffer.from(content).toString('base64'),
            encoding: 'base64',
          });

          treeItems.push({
            path,
            mode: '100644' as const,
            type: 'blob' as const,
            sha: blob.sha,
          });
        }

        // 7. Create a new tree
        const { data: newTree } = await octokit.git.createTree({
          owner: repoOwner,
          repo: repoName,
          tree: treeItems,
          base_tree: latestCommit.tree.sha,
        });

        // 8. Create a commit
        const { data: newCommit } = await octokit.git.createCommit({
          owner: repoOwner,
          repo: repoName,
          message: `🚀 Generated by AI App Generator - ${config.app.name} v${config.app.version}`,
          tree: newTree.sha,
          parents: [latestCommitSha],
        });

        // 9. Update the reference
        const branchName = ref.ref.replace('refs/heads/', '');
        await octokit.git.updateRef({
          owner: repoOwner,
          repo: repoName,
          ref: `heads/${branchName}`,
          sha: newCommit.sha,
        });

        const repoUrl = `https://github.com/${repoOwner}/${repoName}`;
        log.info(`Project exported to GitHub: ${repoUrl}`);

        res.json({
          success: true,
          data: {
            url: repoUrl,
            owner: repoOwner,
            repo: repoName,
            commit: newCommit.sha,
            filesCount: Object.keys(files).length,
          },
        });
      } catch (err: unknown) {
        const message = err instanceof Error ? err.message : String(err);
        log.error(`GitHub export failed: ${message}`);
        throw new AppError(`GitHub export failed: ${message}`, 500);
      }
    })
  );

  return router;
}
